"""Tests for the pure render boundary, contribution composition, and source baseline."""

from __future__ import annotations

import os
import socket
import time
from collections.abc import Iterator, Mapping
from dataclasses import replace
from types import MappingProxyType
from typing import Literal, cast, override

import pytest
from pydantic import ValidationError

from scripts.bootstrap.blobs import ContentId, VerifiedBlobStore
from scripts.bootstrap.contributions import (
    compose_contributions,
    compose_document_bodies,
)
from scripts.bootstrap.errors import ContractError, ContractErrorKind
from scripts.bootstrap.identity import PosixMode, sha256_hex
from scripts.bootstrap.intents import GenerationPath
from scripts.bootstrap.manifest import SlotContent
from scripts.bootstrap.paths import RepoPath
from scripts.bootstrap.render import (
    ArtifactDefinition,
    CapabilityDefinition,
    ContributionDefinition,
    CoreDefinition,
    DocumentFragmentDefinition,
    LicensingInfo,
    MaintenanceInfo,
    MaintenanceSource,
    ProfileInfo,
    ProjectInfo,
    ProjectSource,
    RenderErrorKind,
    RenderInput,
    SettingSource,
    SlotDefinition,
    SubstitutionDefinition,
    _remove_marker_line,  # pyright: ignore[reportPrivateUsage]  deliberate unit test of private render helper
    apply_substitutions,
    derive_managed_inventory,
    encode_scalar,
    render_managed,
)
from scripts.bootstrap.result import Err, Ok
from scripts.bootstrap.source_baseline import (
    CopierSourceBaseline,
    GitHubSourceBaseline,
    LifecycleSourceEntry,
    derive_source_baseline,
    template_source_fingerprint,
)

PROJECT = ProjectInfo(name="example", default_branch="main")
LICENSING = LicensingInfo(mode="retain-apache-2.0", content_sha256=None)
PROFILE = ProfileInfo(id="portable", frozen=())
MAINTENANCE = MaintenanceInfo(status="clean", retained_paths=())
SLOTS: Mapping[str, SlotContent] = MappingProxyType({})


def intern_all(
    store: VerifiedBlobStore, contents: Mapping[str, bytes]
) -> tuple[VerifiedBlobStore, dict[str, ContentId]]:
    content_ids: dict[str, ContentId] = {}
    for key, content in contents.items():
        match store.intern(content):
            case Ok((content_id, updated)):
                content_ids[key] = content_id
                store = updated
            case Err(error):
                raise AssertionError(f"intern failed: {error}")
    return store, content_ids


def intern(
    store: VerifiedBlobStore, content: bytes
) -> tuple[VerifiedBlobStore, ContentId]:
    match store.intern(content):
        case Ok((content_id, updated)):
            return updated, content_id
        case Err(error):
            raise AssertionError(f"intern failed: {error}")


FIXTURE_TEMPLATES: dict[str, bytes] = {
    "tooling": (
        b"[project]\nname = agentic-template:value:project-name\n"
        b"agentic-template:if:strict:begin\n[tool.ruff]\nstrict = true\n"
        b"agentic-template:if:strict:end\n"
    ),
    "ci": b"name: ci\njobs:\nagentic-template:slot:ci-jobs\nagentic-template:slot:release-job\n",
    "releaserc": b'{"branches": [agentic-template:value:channel]}\n',
    "core-job": b"  core-check:\n    runs-on: ubuntu-latest",
    "extra-job": b"  extra:\n    runs-on: ubuntu-latest",
    "audit-job": b"  audit:\n    runs-on: ubuntu-latest",
    "release-job": (
        b"  release:\n    runs-on: ubuntu-latest\n"
        b"    if: github.ref == agentic-template:value:main-branch"
    ),
    "doc-fragment": (
        b"# Capabilities\n\nFrozen expansion for profile **agentic-template:value:project-name**."
    ),
    "doc-tail": b"Generated by bootstrap.",
    "logo": b"\x89PNG\r\n\x1a\nbinary\x00bytes",
    "unused": b"unused output\n",
}

EXPECTED_PYPROJECT = (
    b"[project]\n"
    b'name = "example"\n'
    b'version = "0.1.0"\n'
    b'requires-python = ">=3.14"\n'
    b"dependencies = [\n"
    b'    "pydantic>=2",\n'
    b'    "pyyaml>=6.0.3",\n'
    b"]\n"
)
EXPECTED_CI = (
    b"name: ci\njobs:\n"
    b"  core-check:\n    runs-on: ubuntu-latest\n"
    b"  extra:\n    runs-on: ubuntu-latest\n"
    b"  audit:\n    runs-on: ubuntu-latest\n"
    b"  release:\n    runs-on: ubuntu-latest\n"
    b'    if: github.ref == "main"\n'
)
EXPECTED_RELEASERC = b'{"branches": ["next"]}\n'
EXPECTED_CAPABILITIES = b"# Capabilities\n\nFrozen expansion for profile **example**.\n\nGenerated by bootstrap.\n"


def fixture_blobs() -> tuple[VerifiedBlobStore, dict[str, ContentId]]:
    return intern_all(VerifiedBlobStore.empty(), FIXTURE_TEMPLATES)


def fixture_core(content_ids: Mapping[str, ContentId]) -> CoreDefinition:
    return CoreDefinition(
        artifacts=(
            ArtifactDefinition(
                id="tooling",
                path="tooling.toml",
                kind="text",
                install_mode=0o644,
                template_blob=content_ids["tooling"],
                context="yaml",
                substitutions=(
                    SubstitutionDefinition(
                        name="project-name",
                        source=ProjectSource(kind="project", key="name"),
                    ),
                    SubstitutionDefinition(
                        name="strict",
                        source=SettingSource(
                            kind="setting",
                            capability="semantic-release",
                            setting="strict",
                        ),
                    ),
                ),
            ),
            ArtifactDefinition(
                id="ci",
                path=".github/workflows/ci.yml",
                kind="text",
                install_mode=0o644,
                template_blob=content_ids["ci"],
            ),
            ArtifactDefinition(
                id="logo",
                path="assets/logo.bin",
                kind="binary",
                install_mode=0o644,
                template_blob=content_ids["logo"],
            ),
        ),
        slots=(
            SlotDefinition(
                id="ci-jobs",
                owner_artifact="ci",
                context="yaml",
                separator="\n",
                allowed_contribution_kind="yaml",
            ),
            SlotDefinition(
                id="release-job",
                owner_artifact="ci",
                context="yaml",
                separator="",
                allowed_contribution_kind="yaml",
            ),
        ),
        contributions=(
            ContributionDefinition(
                id="core-check",
                slot="ci-jobs",
                order=0,
                kind="yaml",
                body_blob=content_ids["core-job"],
            ),
        ),
    )


def fixture_capabilities(
    content_ids: Mapping[str, ContentId],
) -> dict[str, CapabilityDefinition]:
    return {
        "semantic-release": CapabilityDefinition(
            id="semantic-release",
            description="Automated semantic releases.",
            artifacts=(
                ArtifactDefinition(
                    id="releaserc",
                    path=".releaserc",
                    kind="text",
                    install_mode=0o644,
                    template_blob=content_ids["releaserc"],
                    context="yaml",
                    substitutions=(
                        SubstitutionDefinition(
                            name="channel",
                            source=SettingSource(
                                kind="setting",
                                capability="semantic-release",
                                setting="channel",
                            ),
                        ),
                    ),
                ),
            ),
            contributions=(
                ContributionDefinition(
                    id="extra",
                    slot="ci-jobs",
                    order=0,
                    kind="yaml",
                    body_blob=content_ids["extra-job"],
                ),
                ContributionDefinition(
                    id="audit",
                    slot="ci-jobs",
                    order=1,
                    kind="yaml",
                    body_blob=content_ids["audit-job"],
                ),
                ContributionDefinition(
                    id="release",
                    slot="release-job",
                    order=0,
                    kind="yaml",
                    body_blob=content_ids["release-job"],
                    substitutions=(
                        SubstitutionDefinition(
                            name="main-branch",
                            source=ProjectSource(kind="project", key="default_branch"),
                        ),
                    ),
                ),
            ),
            document_fragments=(
                DocumentFragmentDefinition(
                    id="capabilities",
                    document="docs/capabilities.md",
                    order=0,
                    body_blob=content_ids["doc-fragment"],
                    substitutions=(
                        SubstitutionDefinition(
                            name="project-name",
                            source=ProjectSource(kind="project", key="name"),
                        ),
                    ),
                ),
                DocumentFragmentDefinition(
                    id="tail",
                    document="docs/capabilities.md",
                    order=1,
                    body_blob=content_ids["doc-tail"],
                ),
            ),
        ),
        "unused": CapabilityDefinition(
            id="unused",
            artifacts=(
                ArtifactDefinition(
                    id="unused-file",
                    path="unused.txt",
                    kind="text",
                    install_mode=0o644,
                    template_blob=content_ids["unused"],
                ),
            ),
        ),
    }


def fixture_settings() -> Mapping[str, Mapping[str, str | bool]]:
    return MappingProxyType({"semantic-release": {"channel": "next", "strict": True}})


def make_render_input(
    store: VerifiedBlobStore,
    content_ids: Mapping[str, ContentId],
    *,
    effective: tuple[str, ...] = ("semantic-release",),
    settings: Mapping[str, Mapping[str, str | bool]] | None = None,
    project: ProjectInfo = PROJECT,
    maintenance: MaintenanceInfo = MAINTENANCE,
) -> RenderInput:
    core = fixture_core(content_ids)
    definitions = fixture_capabilities(content_ids)
    resolved_settings = fixture_settings() if settings is None else settings
    match compose_contributions(
        core,
        definitions,
        effective,
        resolved_settings,
        project,
        maintenance,
        store,
    ):
        case Ok(composed):
            contributions = composed
        case Err(error):
            raise AssertionError(f"contribution composition failed: {error}")
    match compose_document_bodies(
        core,
        definitions,
        effective,
        resolved_settings,
        project,
        maintenance,
        store,
    ):
        case Ok(composed):
            documents = dict(composed)
        case Err(error):
            raise AssertionError(f"document composition failed: {error}")
    return RenderInput(
        render_input_version=1,
        generation_path=GenerationPath.GITHUB,
        project=project,
        licensing=LICENSING,
        profile=PROFILE,
        additions=(),
        effective=effective,
        definitions=MappingProxyType(definitions),
        core=core,
        settings=resolved_settings,
        contributions=contributions,
        documents=MappingProxyType(documents),
        maintenance=maintenance,
        slots=SLOTS,
    )


def render_bytes(
    render_input: RenderInput, store: VerifiedBlobStore
) -> dict[str, bytes]:
    match render_managed(render_input, store):
        case Ok(managed):
            return {file.path.value: file.content for file in managed}
        case Err(error):
            raise AssertionError(f"unexpected render failure: {error}")


def test_rendering_is_byte_identical_across_repeated_calls() -> None:
    store, content_ids = fixture_blobs()
    first = render_bytes(make_render_input(store, content_ids), store)
    second = render_bytes(make_render_input(store, content_ids), store)
    assert first == second
    assert first["pyproject.toml"] == EXPECTED_PYPROJECT
    assert first[".github/workflows/ci.yml"] == EXPECTED_CI
    assert first[".releaserc"] == EXPECTED_RELEASERC
    assert first["docs/capabilities.md"] == EXPECTED_CAPABILITIES
    assert first["assets/logo.bin"] == FIXTURE_TEMPLATES["logo"]


def test_rendering_is_byte_identical_across_input_insertion_orders() -> None:
    store, content_ids = fixture_blobs()
    first = make_render_input(store, content_ids)
    second = replace(
        first,
        settings=MappingProxyType(
            {"semantic-release": {"strict": True, "channel": "next"}}
        ),
    )
    assert render_bytes(first, store) == render_bytes(second, store)


def test_renderer_purity_under_blocked_ambient_access(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fail(*_args: object, **_kwargs: object) -> object:
        raise AssertionError("ambient access attempted")

    class RaisingMapping(Mapping[str, str]):
        @override
        def __getitem__(self, key: str) -> str:
            raise AssertionError("ambient environment access")

        @override
        def __iter__(self) -> Iterator[str]:
            raise AssertionError("ambient environment access")

        @override
        def __len__(self) -> int:
            raise AssertionError("ambient environment access")

    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    with monkeypatch.context() as patcher:
        patcher.setattr("builtins.open", fail)
        patcher.setattr(os, "environ", RaisingMapping())
        patcher.setattr(os, "getcwd", fail)
        patcher.setattr(time, "time", fail)
        patcher.setattr(socket, "socket", fail)
        result = render_managed(render_input, store)
    match result:
        case Ok(_):
            pass
        case Err(error):
            raise AssertionError(f"renderer touched ambient state: {error}")


def test_missing_artifact_blob_fails_before_rendering() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    broken = replace(
        render_input,
        core=render_input.core.model_copy(
            update={
                "artifacts": (
                    *render_input.core.artifacts[:1],
                    render_input.core.artifacts[1].model_copy(
                        update={"template_blob": ContentId("0" * 64)}
                    ),
                    *render_input.core.artifacts[2:],
                )
            }
        ),
    )
    match render_managed(broken, store):
        case Err(error):
            assert error.kind is RenderErrorKind.MISSING_BLOB
            assert error.subject == ".github/workflows/ci.yml"
        case Ok(_):
            raise AssertionError("expected a missing-blob failure")


def test_missing_contribution_blob_fails_before_rendering() -> None:
    store, content_ids = fixture_blobs()
    core = fixture_core(content_ids).model_copy(
        update={
            "contributions": (
                fixture_core(content_ids)
                .contributions[0]
                .model_copy(update={"body_blob": ContentId("f" * 64)}),
            )
        }
    )
    match compose_contributions(
        core,
        fixture_capabilities(content_ids),
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.kind is RenderErrorKind.MISSING_BLOB
        case Ok(_):
            raise AssertionError("expected a missing-blob failure")


def test_missing_document_fragment_blob_fails_before_rendering() -> None:
    store, content_ids = fixture_blobs()
    definitions = fixture_capabilities(content_ids)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "document_fragments": (
                definitions["semantic-release"]
                .document_fragments[0]
                .model_copy(update={"body_blob": ContentId("a" * 64)}),
                definitions["semantic-release"].document_fragments[1],
            )
        }
    )
    match compose_document_bodies(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.kind is RenderErrorKind.MISSING_BLOB
        case Ok(_):
            raise AssertionError("expected a missing-blob failure")


def test_ownership_collision_across_owners_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    definitions = dict(render_input.definitions)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "artifacts": (
                definitions["semantic-release"]
                .artifacts[0]
                .model_copy(update={"path": "pyproject.toml"}),
            )
        }
    )
    match render_managed(
        replace(render_input, definitions=MappingProxyType(definitions)), store
    ):
        case Err(error):
            assert error.kind is RenderErrorKind.OWNERSHIP_COLLISION
            assert error.subject == "pyproject.toml"
        case Ok(_):
            raise AssertionError("expected an ownership collision failure")


def test_document_artifact_path_collision_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    colliding = replace(
        render_input,
        documents=MappingProxyType({RepoPath("pyproject.toml"): ("body",)}),
    )
    match render_managed(colliding, store):
        case Err(error):
            assert error.kind is RenderErrorKind.PATH_COLLISION
            assert error.subject == "pyproject.toml"
        case Ok(_):
            raise AssertionError("expected a path collision failure")


def test_undeclared_document_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    undeclared = replace(
        render_input,
        documents=MappingProxyType({RepoPath("docs/other.md"): ("body",)}),
    )
    match render_managed(undeclared, store):
        case Err(error):
            assert error.kind is RenderErrorKind.UNDECLARED_OUTPUT
            assert error.subject == "docs/other.md"
        case Ok(_):
            raise AssertionError("expected an undeclared-output failure")


def test_managed_inventory_contains_only_managed_output() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    match render_managed(render_input, store):
        case Ok(managed):
            inventory = derive_managed_inventory(managed)
        case Err(error):
            raise AssertionError(f"unexpected render failure: {error}")
    assert tuple(entry.path.value for entry in inventory) == (
        ".github/workflows/ci.yml",
        ".releaserc",
        "assets/logo.bin",
        "docs/capabilities.md",
        "pyproject.toml",
        "tooling.toml",
    )
    by_path = {entry.path.value: entry for entry in inventory}
    assert by_path["pyproject.toml"].mode == PosixMode.FILE
    assert by_path["pyproject.toml"].kind == "text"
    assert by_path["pyproject.toml"].sha256 == sha256_hex(EXPECTED_PYPROJECT)
    assert by_path["tooling.toml"].sha256 == sha256_hex(
        b'[project]\nname = "example"\n[tool.ruff]\nstrict = true\n'
    )
    assert by_path["assets/logo.bin"].sha256 == sha256_hex(FIXTURE_TEMPLATES["logo"])


def test_seed_and_legal_bytes_are_digest_addressed_and_never_managed() -> None:
    seed_bytes = b"# README\n"
    legal_bytes = b"Apache-2.0 license text\n"
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    render_input = replace(
        render_input,
        licensing=LicensingInfo(
            mode="provided-project-license",
            content_sha256=ContentId.from_bytes(legal_bytes).value,
        ),
        slots=MappingProxyType(
            {
                "readme": SlotContent(
                    mode="file", content_sha256=ContentId.from_bytes(seed_bytes).value
                )
            }
        ),
    )
    match render_managed(render_input, store):
        case Ok(managed):
            rendered_paths = {file.path.value for file in managed}
            inventory = derive_managed_inventory(managed)
        case Err(error):
            raise AssertionError(f"unexpected render failure: {error}")
    assert "README.md" not in rendered_paths
    assert "LICENSE" not in rendered_paths
    assert all(entry.path.value not in {"README.md", "LICENSE"} for entry in inventory)


def test_settings_change_changes_output() -> None:
    store, content_ids = fixture_blobs()
    changed_settings = MappingProxyType(
        {"semantic-release": {"channel": "beta", "strict": True}}
    )
    render_input = make_render_input(store, content_ids, settings=changed_settings)
    rendered = render_bytes(render_input, store)
    assert rendered[".releaserc"] == b'{"branches": ["beta"]}\n'


def test_boolean_setting_toggles_optional_section() -> None:
    store, content_ids = fixture_blobs()
    disabled = MappingProxyType(
        {"semantic-release": {"channel": "next", "strict": False}}
    )
    render_input = make_render_input(store, content_ids, settings=disabled)
    rendered = render_bytes(render_input, store)
    assert rendered["tooling.toml"] == b'[project]\nname = "example"\n'
    assert b"ruff" not in rendered["tooling.toml"]


def test_optional_section_requires_normalized_boolean() -> None:
    store, content_ids = fixture_blobs()
    string_control = MappingProxyType(
        {"semantic-release": {"channel": "next", "strict": "true"}}
    )
    render_input = make_render_input(store, content_ids, settings=string_control)
    match render_managed(render_input, store):
        case Err(error):
            assert error.kind is RenderErrorKind.INVALID_TEMPLATE
            assert error.reason == "optional_section_requires_boolean"
        case Ok(_):
            raise AssertionError("expected a boolean-section failure")


def test_retained_paths_must_be_repository_relative() -> None:
    store, content_ids = fixture_blobs()
    kept = make_render_input(
        store,
        content_ids,
        maintenance=MaintenanceInfo(
            status="retained", retained_paths=(RepoPath("docs/keep.md"),)
        ),
    )
    assert kept.maintenance.retained_paths == (RepoPath("docs/keep.md"),)
    with pytest.raises(ValueError, match="retained path"):
        _ = make_render_input(
            store,
            content_ids,
            maintenance=MaintenanceInfo(
                status="retained", retained_paths=(RepoPath("../escape"),)
            ),
        )


def test_unknown_substitution_marker_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, unknown_id = intern(
        store, b'[project]\nname = "agentic-template:value:nope"\n'
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": unknown_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "unknown_substitution"
        case Ok(_):
            raise AssertionError("expected an unknown-substitution failure")


def test_value_marker_prefix_is_not_partially_substituted() -> None:
    result = apply_substitutions(
        b"name = agentic-template:value:repo_url\n",
        (
            SubstitutionDefinition(
                name="repo", source=ProjectSource(kind="project", key="name")
            ),
        ),
        context="markdown",
        settings={},
        project=PROJECT,
        maintenance=MaintenanceInfo(status="clean", retained_paths=()),
    )
    assert result == Ok(b"name = agentic-template:value:repo_url\n")


def test_contribution_order_changes_output() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    assert [c.contribution_id for c in render_input.contributions] == [
        "core-check",
        "extra",
        "release",
        "audit",
    ]
    swapped = replace(
        render_input,
        contributions=(
            render_input.contributions[0],
            render_input.contributions[3],
            render_input.contributions[2],
            render_input.contributions[1],
        ),
    )
    assert render_bytes(render_input, store) != render_bytes(swapped, store)


def test_document_body_change_changes_output() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    changed = replace(
        render_input,
        documents=MappingProxyType(
            {RepoPath("docs/capabilities.md"): ("# Different\n",)}
        ),
    )
    assert render_bytes(render_input, store) != render_bytes(changed, store)


def test_default_branch_flows_through_rendered_output() -> None:
    store, content_ids = fixture_blobs()
    baseline = render_bytes(make_render_input(store, content_ids), store)
    trunk = render_bytes(
        make_render_input(
            store,
            content_ids,
            project=ProjectInfo(name="example", default_branch="trunk"),
        ),
        store,
    )
    assert baseline != trunk
    assert b'"trunk"' in trunk[".github/workflows/ci.yml"]


def test_invalid_default_branch_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    with pytest.raises(ValueError, match="default_branch"):
        _ = replace(
            render_input,
            project=ProjectInfo(name="example", default_branch="bad branch"),
        )


def test_invalid_retained_path_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    with pytest.raises(ValueError, match="retained"):
        _ = replace(
            render_input,
            maintenance=MaintenanceInfo(
                status="retained", retained_paths=(RepoPath("a/../b"),)
            ),
        )


def test_invalid_licensing_digest_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    with pytest.raises(ValueError, match="sha256"):
        _ = replace(
            render_input,
            licensing=LicensingInfo(
                mode="provided-project-license", content_sha256="not-a-digest"
            ),
        )


def test_schema_version_dispatch_rejects_unknown_versions() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    match render_managed(replace(render_input, render_input_version=2), store):
        case Err(error):
            assert error.kind is RenderErrorKind.INVALID_TEMPLATE
            assert error.reason == "unsupported_render_input_version"
        case Ok(_):
            raise AssertionError("expected a schema-version failure")


def test_non_affecting_fields_do_not_change_output() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    provenance_changed = replace(
        render_input,
        generation_path=GenerationPath.COPIER,
        additions=("unused",),
        profile=ProfileInfo(id="integrated", frozen=("unused",)),
    )
    assert render_bytes(render_input, store) == render_bytes(provenance_changed, store)


def test_unselected_capability_definition_has_no_effect() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    assert "unused.txt" not in render_bytes(render_input, store)
    match render_managed(render_input, store):
        case Ok(managed):
            assert all(file.path.value != "unused.txt" for file in managed)
        case Err(error):
            raise AssertionError(f"unexpected render failure: {error}")


def test_missing_definition_for_effective_capability_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    definitions = dict(render_input.definitions)
    del definitions["semantic-release"]
    match render_managed(
        replace(render_input, definitions=MappingProxyType(definitions)), store
    ):
        case Err(error):
            assert error.reason == "missing_capability_definition"
        case Ok(_):
            raise AssertionError("expected a missing-definition failure")


def test_contributions_compose_in_normative_order() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    bodies = [
        contribution.rendered_body
        for contribution in render_input.contributions
        if contribution.slot == "ci-jobs"
    ]
    assert bodies == [
        FIXTURE_TEMPLATES["core-job"].decode(),
        FIXTURE_TEMPLATES["extra-job"].decode(),
        FIXTURE_TEMPLATES["audit-job"].decode(),
    ]


def test_duplicate_contribution_identity_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    core = fixture_core(content_ids).model_copy(
        update={
            "contributions": (
                fixture_core(content_ids).contributions[0],
                fixture_core(content_ids).contributions[0],
            )
        }
    )
    match compose_contributions(
        core,
        fixture_capabilities(content_ids),
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "duplicate_contribution_identity"
        case Ok(_):
            raise AssertionError("expected a duplicate-identity failure")


def test_contribution_to_unknown_slot_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    definitions = fixture_capabilities(content_ids)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "contributions": (
                ContributionDefinition(
                    id="ghost",
                    slot="ghost-slot",
                    order=0,
                    kind="yaml",
                    body_blob=content_ids["extra-job"],
                ),
            )
        }
    )
    match compose_contributions(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "missing_slot"
        case Ok(_):
            raise AssertionError("expected a missing-slot failure")


def test_wrong_contribution_kind_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    definitions = fixture_capabilities(content_ids)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "contributions": (
                ContributionDefinition(
                    id="shell-job",
                    slot="ci-jobs",
                    order=0,
                    kind="shell",
                    body_blob=content_ids["extra-job"],
                ),
            )
        }
    )
    match compose_contributions(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "wrong_kind"
        case Ok(_):
            raise AssertionError("expected a wrong-kind failure")


def test_empty_slot_renders_its_marker_empty() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    render_input = replace(
        render_input,
        contributions=tuple(
            contribution
            for contribution in render_input.contributions
            if contribution.slot != "release-job"
        ),
    )
    rendered = render_bytes(render_input, store)
    assert b"release" not in rendered[".github/workflows/ci.yml"]
    assert b"agentic-template:slot:" not in rendered[".github/workflows/ci.yml"]


def test_missing_slot_marker_in_owner_artifact_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, partial_ci_id = intern(
        store, b"name: ci\njobs:\nagentic-template:slot:ci-jobs\n"
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0],
                render_input.core.artifacts[1].model_copy(
                    update={"template_blob": partial_ci_id}
                ),
                render_input.core.artifacts[2],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "missing_slot_marker"
            assert error.subject == "release-job"
        case Ok(_):
            raise AssertionError("expected a missing-marker failure")


def test_slot_marker_not_owned_by_artifact_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, foreign_id = intern(
        store, b'[project]\nname = "x"\nagentic-template:slot:release-job\n'
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": foreign_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "slot_not_owned_by_artifact"
        case Ok(_):
            raise AssertionError("expected a slot-ownership failure")


def test_unknown_slot_marker_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, ghost_id = intern(
        store, b'[project]\nname = "x"\nagentic-template:slot:ghost\n'
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": ghost_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "unknown_slot_marker"
        case Ok(_):
            raise AssertionError("expected an unknown-slot failure")


def test_unbalanced_optional_section_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, unbalanced_id = intern(
        store, b"[project]\nagentic-template:if:strict:begin\n"
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": unbalanced_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "unbalanced_optional_section"
        case Ok(_):
            raise AssertionError("expected an unbalanced-section failure")


def test_nested_optional_section_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, nested_id = intern(
        store,
        b"agentic-template:if:strict:begin\nagentic-template:if:strict:begin\nx\nagentic-template:if:strict:end\nagentic-template:if:strict:end\n",
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": nested_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "nested_optional_section"
        case Ok(_):
            raise AssertionError("expected a nested-section failure")


def test_text_artifacts_normalize_line_endings() -> None:
    store, content_ids = fixture_blobs()
    store, crlf_id = intern(store, b'[project]\r\nname = "x"\r\n\r\n')
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": crlf_id, "substitutions": ()}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    rendered = render_bytes(replace(render_input, core=core), store)
    assert rendered["tooling.toml"] == b'[project]\nname = "x"\n'


def test_managed_render_is_sorted_by_canonical_path_bytes() -> None:
    store, content_ids = fixture_blobs()
    core = fixture_core(content_ids).model_copy(
        update={
            "artifacts": (
                ArtifactDefinition(
                    id="dash",
                    path="a-b.txt",
                    kind="text",
                    install_mode=0o644,
                    template_blob=content_ids["unused"],
                ),
                ArtifactDefinition(
                    id="slash",
                    path="a/b.txt",
                    kind="text",
                    install_mode=0o644,
                    template_blob=content_ids["unused"],
                ),
            ),
            "slots": (),
            "contributions": (),
        }
    )
    render_input = make_render_input(store, content_ids)
    render_input = replace(
        render_input,
        core=core,
        contributions=(),
        documents=MappingProxyType({}),
        definitions=MappingProxyType({}),
        effective=(),
    )
    match render_managed(render_input, store):
        case Ok(managed):
            assert [file.path.value for file in managed] == [
                "a-b.txt",
                "a/b.txt",
                "pyproject.toml",
            ]
        case Err(error):
            raise AssertionError(f"unexpected render failure: {error}")


def test_encode_scalar_uses_declared_context() -> None:
    assert encode_scalar("plain", "yaml") == '"plain"'
    assert encode_scalar("hello world", "yaml") == '"hello world"'
    assert encode_scalar("true", "yaml") == '"true"'
    assert encode_scalar("True", "yaml") == '"True"'
    assert encode_scalar("YES", "yaml") == '"YES"'
    assert encode_scalar("123", "yaml") == '"123"'
    assert encode_scalar("1e5", "yaml") == '"1e5"'
    assert encode_scalar("line\nbreak", "yaml") == '"line\\nbreak"'
    assert encode_scalar(True, "yaml") == "true"
    assert encode_scalar("raw **markdown**", "markdown") == "raw **markdown**"
    assert encode_scalar(True, "markdown") == "true"


def test_core_definition_rejects_invalid_shapes() -> None:
    _store, content_ids = fixture_blobs()
    core = fixture_core(content_ids)
    with pytest.raises(ValidationError):
        _ = CoreDefinition(
            artifacts=core.artifacts,
            slots=(core.slots[0].model_copy(update={"owner_artifact": "missing"}),),
            contributions=core.contributions,
        )
    with pytest.raises(ValidationError):
        _ = CoreDefinition(
            artifacts=(core.artifacts[0], core.artifacts[0]),
            slots=core.slots,
            contributions=core.contributions,
        )
    with pytest.raises(ValidationError):
        _ = ArtifactDefinition(
            id="contextless",
            path="x.txt",
            kind="text",
            install_mode=0o644,
            template_blob=content_ids["unused"],
            substitutions=(
                SubstitutionDefinition(
                    name="v", source=ProjectSource(kind="project", key="name")
                ),
            ),
        )
    with pytest.raises(ValidationError):
        _ = ArtifactDefinition(
            id="bad-blob",
            path="x.txt",
            kind="text",
            install_mode=0o644,
            template_blob=cast(ContentId, "not-a-digest"),  # pyright: ignore[reportInvalidCast]  intentional invalid-value negative test
        )


def test_duplicate_fragment_identity_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    definitions = fixture_capabilities(content_ids)
    fragment = definitions["semantic-release"].document_fragments[0]
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={"document_fragments": (fragment, fragment)}
    )
    match compose_document_bodies(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "duplicate_fragment_identity"
        case Ok(_):
            raise AssertionError("expected a duplicate-fragment failure")


def test_capability_named_core_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    definitions = fixture_capabilities(content_ids)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={"id": "core"}
    )
    match compose_contributions(
        fixture_core(content_ids),
        definitions,
        ("core",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "reserved_owner"
        case Ok(_):
            raise AssertionError("expected a reserved-owner failure")


def test_source_baseline_fingerprint_is_deterministic_and_tagged() -> None:
    entries = (
        LifecycleSourceEntry(
            path=RepoPath("b.txt"), kind="file", mode=PosixMode.FILE, sha256="b" * 64
        ),
        LifecycleSourceEntry(
            path=RepoPath("a.txt"), kind="file", mode=PosixMode.FILE, sha256="a" * 64
        ),
    )
    first = template_source_fingerprint(entries)
    assert first == template_source_fingerprint(entries)
    assert first == template_source_fingerprint(tuple(reversed(entries)))
    assert first != template_source_fingerprint(
        (
            LifecycleSourceEntry(
                path=RepoPath("a.txt"),
                kind="file",
                mode=PosixMode.FILE,
                sha256="c" * 64,
            ),
            entries[0],
        )
    )


def test_github_baseline_requires_snapshot_commit() -> None:
    entries = (
        LifecycleSourceEntry(
            path=RepoPath("a.txt"), kind="file", mode=PosixMode.FILE, sha256="a" * 64
        ),
    )
    commit = "a" * 40
    match derive_source_baseline(
        GenerationPath.GITHUB, entries, snapshot_commit=commit
    ):
        case Ok(GitHubSourceBaseline() as baseline):
            assert baseline.snapshot_commit == commit
            assert baseline.entries == entries
        case Ok(CopierSourceBaseline()):
            raise AssertionError("expected a GitHub source baseline")
        case Err(error):
            raise AssertionError(f"unexpected source baseline failure: {error}")
        case Ok(_):
            raise AssertionError("unexpected source baseline variant")
    for invalid in (None, "", "   ", "not-a-commit", "ABC" * 20):
        match derive_source_baseline(
            GenerationPath.GITHUB, entries, snapshot_commit=invalid
        ):
            case Err(error):
                assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
            case Ok(_):
                raise AssertionError("expected a snapshot-commit failure")


def test_copier_baseline_rejects_snapshot_commit() -> None:
    entries = (
        LifecycleSourceEntry(
            path=RepoPath("a.txt"), kind="file", mode=PosixMode.FILE, sha256="a" * 64
        ),
    )
    match derive_source_baseline(GenerationPath.COPIER, entries):
        case Ok(CopierSourceBaseline() as baseline):
            assert baseline.entries == entries
        case Ok(GitHubSourceBaseline()):
            raise AssertionError("expected a Copier source baseline")
        case Err(error):
            raise AssertionError(f"unexpected source baseline failure: {error}")
        case Ok(_):
            raise AssertionError("unexpected source baseline variant")
    match derive_source_baseline(GenerationPath.COPIER, entries, snapshot_commit="abc"):
        case Err(error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected a snapshot-commit rejection")


def test_source_baseline_rejects_duplicate_and_unsafe_entries() -> None:
    entry = LifecycleSourceEntry(
        path=RepoPath("a.txt"), kind="file", mode=PosixMode.FILE, sha256="a" * 64
    )
    match derive_source_baseline(
        GenerationPath.GITHUB, (entry, entry), snapshot_commit="abc"
    ):
        case Err(error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected a duplicate-entry failure")
    match derive_source_baseline(
        GenerationPath.GITHUB,
        (
            LifecycleSourceEntry(
                path=RepoPath("../a.txt"),
                kind="file",
                mode=PosixMode.FILE,
                sha256="a" * 64,
            ),
        ),
        snapshot_commit="abc",
    ):
        case Err(error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected an unsafe-path failure")


def test_source_baseline_rejects_invalid_mode_for_kind() -> None:
    match derive_source_baseline(
        GenerationPath.GITHUB,
        (
            LifecycleSourceEntry(
                path=RepoPath("dir"),
                kind="directory",
                mode=PosixMode.FILE,
                sha256="a" * 64,
            ),
        ),
        snapshot_commit="abc",
    ):
        case Err(error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected a mode/kind failure")


def test_contract_error_is_used_for_source_baseline_failures() -> None:
    match derive_source_baseline(
        GenerationPath.GITHUB,
        (
            LifecycleSourceEntry(
                path=RepoPath("a.txt"), kind="file", mode=PosixMode.FILE, sha256="nope"
            ),
        ),
        snapshot_commit="abc",
    ):
        case Err(ContractError() as error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected a source-contract failure")


def test_source_baseline_rejects_invalid_kind_and_file_modes() -> None:
    match derive_source_baseline(
        GenerationPath.GITHUB,
        (
            LifecycleSourceEntry(
                path=RepoPath("a.txt"),
                kind=cast(Literal["file", "directory"], "weird"),  # pyright: ignore[reportInvalidCast]  intentional invalid-value negative test
                mode=PosixMode.FILE,
                sha256="a" * 64,
            ),
        ),
        snapshot_commit="abc",
    ):
        case Err(error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected a kind failure")
    match derive_source_baseline(
        GenerationPath.GITHUB,
        (
            LifecycleSourceEntry(
                path=RepoPath("a.txt"),
                kind="file",
                mode=PosixMode(0o777),
                sha256="a" * 64,
            ),
        ),
        snapshot_commit="abc",
    ):
        case Err(error):
            assert error.kind is ContractErrorKind.SOURCE_CONTRACT_INVALID
        case Ok(_):
            raise AssertionError("expected a mode failure")


def test_content_id_accepts_plain_hex_string() -> None:
    artifact = ArtifactDefinition(
        id="hex-blob",
        path="x.txt",
        kind="text",
        install_mode=0o644,
        template_blob=cast(ContentId, "0" * 64),  # pyright: ignore[reportInvalidCast]  intentional raw-hex-string input
    )
    assert artifact.template_blob == ContentId("0" * 64)


def test_artifact_definition_rejects_unsafe_path_and_duplicate_substitutions() -> None:
    with pytest.raises(ValidationError):
        _ = ArtifactDefinition(
            id="unsafe",
            path="../unsafe",
            kind="text",
            install_mode=0o644,
            template_blob=cast(ContentId, "a" * 64),  # pyright: ignore[reportInvalidCast]  intentional raw-hex-string input
        )
    substitution = SubstitutionDefinition(
        name="value", source=ProjectSource(kind="project", key="name")
    )
    with pytest.raises(ValidationError):
        _ = ArtifactDefinition(
            id="dups",
            path="x.txt",
            kind="text",
            install_mode=0o644,
            template_blob=cast(ContentId, "a" * 64),  # pyright: ignore[reportInvalidCast]  intentional raw-hex-string input
            substitutions=(substitution, substitution),
        )


def test_core_and_capability_definitions_reject_missing_and_duplicate_members() -> None:
    _store, content_ids = fixture_blobs()
    core = fixture_core(content_ids)
    with pytest.raises(ValidationError):
        _ = CoreDefinition(
            artifacts=core.artifacts,
            slots=core.slots,
            contributions=(
                ContributionDefinition(
                    id="ghost",
                    slot="ghost-slot",
                    order=0,
                    kind="yaml",
                    body_blob=content_ids["core-job"],
                ),
            ),
        )
    with pytest.raises(ValidationError):
        _ = CapabilityDefinition(
            id="dups",
            artifacts=(core.artifacts[0], core.artifacts[0]),
        )
    duplicate_path = ArtifactDefinition(
        id="other",
        path=core.artifacts[0].path,
        kind="text",
        install_mode=0o644,
        template_blob=cast(ContentId, "a" * 64),  # pyright: ignore[reportInvalidCast]  intentional raw-hex-string input
    )
    with pytest.raises(ValidationError):
        _ = CoreDefinition(
            artifacts=(core.artifacts[0], duplicate_path),
            slots=core.slots,
            contributions=core.contributions,
        )
    with pytest.raises(ValidationError):
        _ = CapabilityDefinition(
            id="dup-paths",
            artifacts=(core.artifacts[0], duplicate_path),
        )


def test_missing_substitution_value_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, broken_body = intern(
        store, b"  broken:\n    value: agentic-template:value:ghost\n"
    )
    definitions = fixture_capabilities(content_ids)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "contributions": (
                *definitions["semantic-release"].contributions,
                ContributionDefinition(
                    id="broken",
                    slot="ci-jobs",
                    order=0,
                    kind="yaml",
                    body_blob=broken_body,
                    substitutions=(
                        SubstitutionDefinition(
                            name="ghost",
                            source=SettingSource(
                                kind="setting",
                                capability="semantic-release",
                                setting="ghost",
                            ),
                        ),
                    ),
                ),
            )
        }
    )
    match compose_contributions(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "missing_substitution_value"
        case Ok(_):
            raise AssertionError("expected a missing-substitution failure")


def test_invalid_utf8_contribution_body_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, invalid_id = intern(store, b"\xff\xfe binary body")
    core = fixture_core(content_ids).model_copy(
        update={
            "contributions": (
                fixture_core(content_ids)
                .contributions[0]
                .model_copy(update={"body_blob": invalid_id}),
            )
        }
    )
    match compose_contributions(
        core,
        fixture_capabilities(content_ids),
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "body_encoding"
        case Ok(_):
            raise AssertionError("expected a body-encoding failure")


def test_composition_rejects_missing_definition() -> None:
    store, content_ids = fixture_blobs()
    match compose_contributions(
        fixture_core(content_ids),
        fixture_capabilities(content_ids),
        ("missing-cap",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "missing_capability_definition"
        case Ok(_):
            raise AssertionError("expected a missing-definition failure")


def test_document_composition_rejects_reserved_owner_and_missing_definition() -> None:
    store, content_ids = fixture_blobs()
    core = fixture_core(content_ids)
    definitions = fixture_capabilities(content_ids)
    match compose_document_bodies(
        core,
        definitions,
        ("core",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "reserved_owner"
        case Ok(_):
            raise AssertionError("expected a reserved-owner failure")
    match compose_document_bodies(
        core,
        definitions,
        ("missing-cap",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "missing_capability_definition"
        case Ok(_):
            raise AssertionError("expected a missing-definition failure")


def test_document_fragment_substitution_failures_are_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, invalid_id = intern(store, b"\xff\xfe fragment")
    definitions = fixture_capabilities(content_ids)
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "document_fragments": (
                DocumentFragmentDefinition(
                    id="broken",
                    document="docs/capabilities.md",
                    order=0,
                    body_blob=content_ids["doc-fragment"],
                ),
            )
        }
    )
    match compose_document_bodies(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "unknown_substitution"
        case Ok(_):
            raise AssertionError("expected an unknown-substitution failure")
    definitions["semantic-release"] = definitions["semantic-release"].model_copy(
        update={
            "document_fragments": (
                DocumentFragmentDefinition(
                    id="broken",
                    document="docs/capabilities.md",
                    order=0,
                    body_blob=invalid_id,
                ),
            )
        }
    )
    match compose_document_bodies(
        fixture_core(content_ids),
        definitions,
        ("semantic-release",),
        fixture_settings(),
        PROJECT,
        MAINTENANCE,
        store,
    ):
        case Err(error):
            assert error.reason == "body_encoding"
        case Ok(_):
            raise AssertionError("expected a body-encoding failure")


def test_render_input_rejects_invalid_shapes() -> None:
    store, content_ids = fixture_blobs()
    render_input = make_render_input(store, content_ids)
    with pytest.raises(ValueError, match="generation_path"):
        _ = replace(
            render_input,
            generation_path=cast(GenerationPath, "github"),  # pyright: ignore[reportInvalidCast]  intentional invalid-value negative test
        )
    with pytest.raises(ValueError, match="project name"):
        _ = replace(
            render_input, project=ProjectInfo(name="bad name", default_branch="main")
        )
    with pytest.raises(ValueError, match="licensing mode"):
        _ = replace(
            render_input, licensing=LicensingInfo(mode="other", content_sha256=None)
        )
    with pytest.raises(ValueError, match="capability id"):
        _ = replace(render_input, effective=("Bad-ID",))
    with pytest.raises(ValueError, match="slot mode"):
        _ = replace(
            render_input,
            slots=MappingProxyType(
                {"readme": SlotContent(mode="other", content_sha256=None)}
            ),
        )
    with pytest.raises(ValueError, match="document path"):
        _ = replace(
            render_input,
            documents=MappingProxyType({RepoPath("../x.md"): ("body",)}),
        )


def test_optional_section_markers_at_line_and_file_boundaries() -> None:
    store, content_ids = fixture_blobs()
    store, eof_id = intern(
        store,
        b"[project]\nname = x\nagentic-template:if:strict:begin\n[tool.ruff]\nstrict = true\nagentic-template:if:strict:end",
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": eof_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    rendered = render_bytes(replace(render_input, core=core), store)
    assert rendered["tooling.toml"] == (
        b"[project]\nname = x\n[tool.ruff]\nstrict = true\n"
    )
    store, indented_id = intern(
        store,
        b"[project]\n  agentic-template:if:strict:begin\n[tool.ruff]\nstrict = true\n  agentic-template:if:strict:end\n",
    )
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": indented_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    rendered = render_bytes(replace(render_input, core=core), store)
    assert rendered["tooling.toml"] == b"[project]\n[tool.ruff]\nstrict = true\n"
    store, inline_id = intern(
        store,
        b"prefix agentic-template:if:strict:begin mid agentic-template:if:strict:end suffix",
    )
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": inline_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    rendered = render_bytes(replace(render_input, core=core), store)
    assert rendered["tooling.toml"] == b"prefix  mid  suffix\n"
    disabled = MappingProxyType(
        {"semantic-release": {"channel": "next", "strict": False}}
    )
    render_input = make_render_input(store, content_ids, settings=disabled)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": eof_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    rendered = render_bytes(replace(render_input, core=core), store)
    assert rendered["tooling.toml"] == b"[project]\nname = x\n"


def test_remove_marker_line_is_total_and_line_aware() -> None:
    assert _remove_marker_line(b"abc", b"missing") == b"abc"
    assert _remove_marker_line(b"  marker\nrest\n", b"marker") == b"rest\n"
    assert _remove_marker_line(b"  marker", b"marker") == b""
    assert _remove_marker_line(b"prefix marker\n", b"marker") == b"prefix "
    assert _remove_marker_line(b"prefix marker", b"marker") == b"prefix "


def test_optional_section_marker_unknown_name_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, template_id = intern(
        store,
        b"[project]\nagentic-template:if:ghost:begin\nx\nagentic-template:if:ghost:end\n",
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": template_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "unknown_substitution"
        case Ok(_):
            raise AssertionError("expected an unknown-section failure")


def test_optional_section_end_without_begin_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, template_id = intern(store, b"[project]\nagentic-template:if:strict:end\n")
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": template_id}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "unbalanced_optional_section"
        case Ok(_):
            raise AssertionError("expected an unbalanced-section failure")


def test_optional_section_mismatched_names_are_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, template_id = intern(
        store,
        b"[project]\nagentic-template:if:strict:begin\nagentic-template:if:other:end\n",
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={
                        "template_blob": template_id,
                        "substitutions": (
                            *render_input.core.artifacts[0].substitutions,
                            SubstitutionDefinition(
                                name="other",
                                source=ProjectSource(kind="project", key="name"),
                            ),
                        ),
                    }
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "unbalanced_optional_section"
        case Ok(_):
            raise AssertionError("expected a mismatched-section failure")


def test_maintenance_substitutions_render_retained_paths() -> None:
    result = apply_substitutions(
        b"status = agentic-template:value:status\nretained = agentic-template:value:kept\n",
        (
            SubstitutionDefinition(
                name="status",
                source=MaintenanceSource(kind="maintenance", key="status"),
            ),
            SubstitutionDefinition(
                name="kept",
                source=MaintenanceSource(kind="maintenance", key="retained_paths"),
            ),
        ),
        context="markdown",
        settings=fixture_settings(),
        project=PROJECT,
        maintenance=MaintenanceInfo(
            status="retained",
            retained_paths=(RepoPath("a.txt"), RepoPath("b/c.txt")),
        ),
    )
    match result:
        case Ok(rendered):
            assert rendered == b"status = retained\nretained = a.txt\nb/c.txt\n"
        case Err(error):
            raise AssertionError(f"unexpected substitution failure: {error}")


def test_optional_section_missing_substitution_value_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, template_id = intern(
        store, b"agentic-template:if:ghost:begin\nx\nagentic-template:if:ghost:end\n"
    )
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={
                        "template_blob": template_id,
                        "substitutions": (
                            *render_input.core.artifacts[0].substitutions,
                            SubstitutionDefinition(
                                name="ghost",
                                source=SettingSource(
                                    kind="setting",
                                    capability="semantic-release",
                                    setting="ghost",
                                ),
                            ),
                        ),
                    }
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "missing_substitution_value"
        case Ok(_):
            raise AssertionError("expected a missing-substitution failure")


def test_value_marker_without_declared_context_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, template_id = intern(store, b"name = agentic-template:value:anything\n")
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={
                        "template_blob": template_id,
                        "substitutions": (),
                        "context": None,
                    }
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.reason == "missing_artifact_context"
        case Ok(_):
            raise AssertionError("expected a context failure")


def test_invalid_utf8_text_artifact_is_rejected() -> None:
    store, content_ids = fixture_blobs()
    store, invalid_id = intern(store, b"[project]\nname = \xff\xfe\n")
    render_input = make_render_input(store, content_ids)
    core = render_input.core.model_copy(
        update={
            "artifacts": (
                render_input.core.artifacts[0].model_copy(
                    update={"template_blob": invalid_id, "substitutions": ()}
                ),
                *render_input.core.artifacts[1:],
            )
        }
    )
    match render_managed(replace(render_input, core=core), store):
        case Err(error):
            assert error.kind is RenderErrorKind.INVALID_TEMPLATE
            assert error.reason == "text_artifact_encoding"
        case Ok(_):
            raise AssertionError("expected a text-encoding failure")
